# This workflow creates a Unity license request file, which needs to be activated at 
# https://license.unity3d.com/manual
#
# Once the license is activated via that link a file will be returned. Copy and paste the 
# contents of that file to secrets.UNITY_LICENSE
#
# Once Stef has given me the IBM license, this shouldn't be needed anymore as it activates personal licenses

name: Create Unity License Activation File

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2.0-alpha-1
        with:
          unityVersion: 2020.2.1f1
    
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
